services:
  trinity_ollama:
    image: ollama/ollama:latest
    container_name: trinity_ollama_container
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - "44"

  ai_backend:
    build: 
      context: .        
      dockerfile: Dockerfile.amd
    container_name: trinity_ai_container
    restart: always
    tty: true
    stdin_open: true
    privileged: true
    depends_on:
      - trinity_db
      - trinity_ollama
      - trinity_redis_ai 
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - "44"
      - "990"
    command: python AI/generative.py
    environment:
      - HSA_OVERRIDE_GFX_VERSION=11.0.0
      - OLLAMA_BASE_URL=http://trinity_ollama:11434
      - FLASK_RUN_HOST=0.0.0.0
      - ROCM_PATH=/opt/rocm
    volumes:
      - .:/workspace    
    working_dir: /workspace
    networks:          
      - trinity_net
    extra_hosts:
      - "host.docker.internal:host-gateway"


networks:
  trinity_net:
    driver: bridge