version: '3.8'

services:

  ai_chat_backend:
    build: 
      context: .        
      dockerfile: Dockerfile.cpu 
    container_name: trinity_chat_container
    restart: always 
    depends_on:
      - trinity_db
      - trinity_ollama
      - trinity_redis_ai    
    command: python AI/llm.py
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_BASE_URL=http://trinity_ollama:11434
      - REDIS_AI_HOST=trinity_redis_ai
      - REDIS_AI_PORT=6379
      - PYTHONUNBUFFERED=1 
    volumes:
      - .:/workspace
    working_dir: /workspace
    networks:          
      - trinity_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  trinity_ollama:
    image: ollama/ollama:latest
    container_name: trinity_ollama_container
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_VULKAN=true
      - OLLAMA_IGPU_ENABLE=1
      - GGML_VK_VISIBLE_DEVICES=0
    devices: 
      - /dev/kfd:/dev/kfd  
      - /dev/dri:/dev/dri 
    networks:
      - trinity_net

volumes:
  ollama_storage:

networks:
  trinity_net:
    driver: bridge