version: '3.8'

services:
  trinity_db:
    image: mysql:8.0
    container_name: trinity_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tf_database
    ports:
      - "3306:3306"
    volumes:
      - trinity_db_data:/var/lib/mysql
      - ./database_init:/docker-entrypoint-initdb.d
    networks:                     
      - trinity_net
    healthcheck:                    
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 5

  trinity_redis_mail:
    image: redis:alpine
    container_name: trinity_redis_mail_container
    restart: always
    ports:
      - "6379:6379"  
    volumes:
      - trinity_redis_mail_data:/data
    networks:                     
      - trinity_net

  trinity_redis_ai:
    image: redis:alpine
    container_name: trinity_redis_ai_container
    restart: always
    command: ["redis-server", "--protected-mode", "no", "--bind", "0.0.0.0"]
    ports:
      - "6380:6379" 
    volumes:
      - trinity_redis_ai_data:/data
    networks:                     
      - trinity_net

  web_xampp:
    build:
      context: .        
      dockerfile: Dockerfile.web 
    container_name: trinity_style_web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html 
    environment:
      - REDIS_AI_HOST=trinity_redis_ai       
      - REDIS_MAIL_HOST=trinity_redis_mail 
      - REDIS_PORT=6379                    
      - DB_HOST=trinity_db
    networks:
      - trinity_net
    depends_on:
      trinity_db:
        condition: service_healthy    
      trinity_redis_mail:
        condition: service_started
      trinity_redis_ai:
        condition: service_started

  worker_mail:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: redis_mail_service
    restart: always
    command: php /var/www/html/Database/worker.php
    volumes:
      - .:/var/www/html
    environment:                       
      - REDIS_HOST=trinity_redis_mail   
      - REDIS_MAIL_HOST=trinity_redis_mail
      - REDIS_PORT=6379
      - DB_HOST=trinity_db
    networks:                         
      - trinity_net
    depends_on:
      trinity_db:
        condition: service_healthy
      trinity_redis_mail:
        condition: service_started

  worker_ai:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: redis_ai_service
    restart: always
    command: python /app/Database/worker.py
    volumes:
      - .:/app
    depends_on:
      - trinity_redis_ai                  
    environment:
      - REDIS_AI_HOST=trinity_redis_ai 
      - REDIS_PORT=6379                   
      - PYTHONUNBUFFERED=1
    networks:                            
      - trinity_net

volumes:
  trinity_db_data:
  trinity_redis_mail_data:                
  trinity_redis_ai_data:                  
  ollama_storage:
  
networks:
  trinity_net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400